name: release with onlySource.zip

on:
  push:    
    tags:
    - '*'      

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: src/ 
          dest: ${{ github.repository }}_src.zip
      - name: Check to Release file
        run: |
          pwd
          ls -la           
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "onlySource.zip"
          bodyFile: "RELEASE.md"
          token: ${{ secrets.RELEASE_TOKEN }}      
